### ISSUE TITLE
I tried to use the email option and download purchased comics but an error occurs.

### ISSUE THREAD

**Issue by zakipon** [catsital/pyccoma#3]
I tried to use the email option and download purchased comics but an error occurs.

How can I solve this problem?
I have logged in to the web version and confirmed that I have the purchased titles on my bookshelf.
(manga volume)

[cmd]
pyccoma purchase --region jp --filter all --include is_purchased --email foo@bar.com

[log]
07/26/2024 13:52:09 -  info   -      login       - Successfully logged in as foo@bar.com
07/26/2024 13:52:09 -  error  -    get_bdata     - Failed to parse library.
usage: pyccoma [-o OUTPUT] [-f FORMAT] [-p LENGTH] [--archive] [--omit-author] [--region REGION] [--retry-count COUNT]
               [--retry-interval SECONDS] [--email EMAIL] [--etype MANGA SMARTOON NOVEL] [--filter FILTER]
               [--range START END] [--include INCLUDE] [--exclude EXCLUDE] [-l LEVEL] [-h] [-v]
               [url ...]
pyccoma: error: 'NoneType' object has no attribute 'values'

**Comment by catsital** [comment]
Hello! Thank you for reporting this issue. It seems that the elements are now dynamically generated on those pages, hence the parser is not returning anything.  Please try updating to the latest release for the fix and see if it works now. Thanks again!

**Comment by zakipon** [comment]
Thank you for the correction.

We have confirmed that you can DL the purchased works with the corrected v0.7.0.
